### ISSUE TITLE
Failed to compile the scripts

### ISSUE THREAD

**Issue by Harry-Zhang-927** [toshusai/vega#13]
Hi,
I am a Year 2 student from Nanyang Technological University. I am now working on the online video editor and find your amazing project here.
However, when I followed the instructions you have made, I encountered one problem. The problem is as follow:
1. when I try "npm run dev", it will show pop up the error messages: 

**[2386665:0512/101921.414009:ERROR:browser_main_loop.cc(1400)] Unable to open X display.
The futex facility returned an unexpected error code.
/home/haoran/Projects/vega/node_modules/electron/dist/electron exited with signal SIGABRT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vega@0.0.16 dev:main:electron: `cross-env NODE_ENV=development electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vega@0.0.16 dev:main:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/haoran/.npm/_logs/2022-05-12T02_19_21_524Z-debug.log
ERROR: "dev:main:electron" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vega@0.0.16 dev:main: `npm-run-all -s dev:main:tsc dev:main:electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vega@0.0.16 dev:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/haoran/.npm/_logs/2022-05-12T02_19_21_670Z-debug.log
ERROR: "dev:main" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vega@0.0.16 dev: `npm-run-all -p dev:renderer dev:main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vega@0.0.16 dev script.**

In order to solve this, I tried to delete the node_modules and package_lock.json files, also cleaned the cache and restored the node_modules and package_lock.json files again, however, the same problem came up again.

I will be very appreciated if you could help me with it!
Wish you a happy day!

**Comment by toshusai** [comment]
Are you using WSL or a headless environment? It work in OSX.
Also, you can run without electron.

Related question in Stackoverflow: https://stackoverflow.com/questions/69476339/electronjs-unable-to-open-x-display
