### ISSUE TITLE
An index signature parameter type must be either 'string' or 'number'.

### ISSUE THREAD

**Issue by augerjk** [toshusai/vega#14]
`npm run dev

> vega@0.0.16 dev
> npm-run-all -p dev:renderer dev:main

> vega@0.0.16 dev:renderer
> cross-env NODE_ENV=development nuxt src/renderer

> vega@0.0.16 dev:main
> npm-run-all -s dev:main:tsc dev:main:electron

> vega@0.0.16 dev:main:tsc
> cross-env NODE_ENV=development tsc -p src/main/tsconfig.json

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   client-side          │
   │   ▸ Target:      static               │
   │                                       │
   │   Listening: http://localhost:9999/   │
   │                                       │
   ╰───────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                       02:33:55
ℹ Initial build may take a while                                                                                                                          02:33:55
✔ Builder initialized                                                                                                                                     02:33:55
✔ Nuxt files generated                                                                                                                                    02:33:55

● Client █████████████████████████ building (57%) 393/418 modules 25 active
 babel-loader › ts-loader › vue-loader › src/renderer/components/timeline_panel/TimelinePanel.vue

node_modules/vue/types/jsx.d.ts:39:4 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

39   [v: `--${string}`]: string | number | undefined
      ~

● Client █████████████████████████ building (57%) 396/418 modules 22 active
 babel-loader › ts-loader › vue-loader › src/renderer/components/timeline_panel/TimelinePanel.vue

ERROR: "dev:main" exited with 1.`

**Comment by toshusai** [comment]
Sorry, I won't maintenance v1. I work in progress v2 with Nuxt3.
