### ISSUE TITLE
image transprent

### ISSUE THREAD

**Issue by gyanyanendrapratp** [toshusai/vega#15]
Hi, 
I am added one image. the image didn't transparent. 
I have also a tray multiple ways it's not working.
Please provide solution.

![video_editorIssue](https://user-images.githubusercontent.com/49753184/183888080-444aed1c-01d0-48d7-a8f5-fd301e5928cf.png)
  
Thank you

**Comment by toshusai** [comment]
Sorry, this version is no longer maintenance, but I think need this options to ImageStrip.

TextStrip material.
https://github.com/toshusai/vega/blob/master/src/renderer/models/strips/TextStrip.ts#L142
```
      transparent: true,
      depthTest: true,
      depthWrite: false,
      opacity: 1,
      blending: CustomBlending,
      blendSrc: OneFactor,
      blendDst: OneMinusSrcAlphaFactor,
      blendEquation: AddEquation,
```

ImageStrip material.
https://github.com/toshusai/vega/blob/master/src/renderer/models/strips/ImageStrip.ts#L75
