### ISSUE TITLE
How can I add frames in a video strip instead of that wave?

### ISSUE THREAD

**Issue by prarthanashr04** [toshusai/vega#16]
I am having trouble while Converting a video to  frames in video strip of timeline . Can you help me with this?  
![veedss](https://user-images.githubusercontent.com/60914533/184078493-c3cf97c0-be8d-4606-9598-18dbe2d9cabf.png)
I need strip like this image.

**Comment by akshim1702** [comment]
I also have the same issue can you please help me on this @toshusai

**Comment by prarthanashr04** [comment]
Thank You

**Comment by prarthanashr04** [comment]
Hi @toshusai  , Can you send me a tutorial or an article where I can better understand this concept ?

**Comment by toshusai** [comment]
@prarthanashr04 The article is [here](https://dev.to/toshusai/how-to-create-a-video-editor-that-works-in-your-browser-5akh) but as mentioned above, I develop new version. When I release v2, I might create some docs.

**Comment by prarthanashr04** [comment]
Thanks and yes I would appreciate documentation

**Comment by prarthanashr04** [comment]
Hi @toshusai , I checked the code you referred but not able to understand much as I am not familiar with this version , is above feature possible in version 0.0.16? If yes , How?

**Comment by toshusai** [comment]
@prarthanashr04 Basic ideas are same, so it's not impossible. But, I don't update old versions anymore.

**Comment by prarthanashr04** [comment]
@toshusai When  Vega version 2 will be completed?

**Comment by toshusai** [comment]
@prarthanashr04 I merge to master yesterday, but it is still WIP.
