### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by Vort** [toshusai/Vega#24]
Things I tried:
Vivaldi 5.5.2794.3:
1. Created new project
2. Added two text objects
3. Saved project
4. Exported video

Result: It exported file. With incorrect duration (10 sec instead of 15) and black screen as content.
Firefox 103.0.2:
1. Opened previously saved project.
2. Text objects are there, but have no text and I can't see how to add it back.
3. Tried to export video, but clicking on "export" button do nothing.
---
How to delete created text object by the way?

**Comment by toshusai** [comment]
Browser version supports only Google Chrome.

You can delete strips by selecting strip and press X key.

**Comment by Vort** [comment]
I tried also with Chrome 106.0.5249.91.
Result is the same: random length file with black contents. Also text randomly disappears.
I looked in logs and I see this message: `Failed to load resource: the server responded with a status of 404 ()` (`https://toshusai.github.io/scripts/require.js`). May it be related to the problem?
> You can delete strips by selecting strip and press X key.

Ok. It is better to present hotkeys to users in UI. They should not guess or look into code.

**Comment by toshusai** [comment]
I fix requirejs problem, but I think it doesn't related probably.

> Ok. It is better to present hotkeys to users in UI. They should not guess or look into code.
You right, this is an early project, so sorry for lack of documentations.

Can you open and export as webm `demo_project.json`? Or please share your project.json, you can download File > Save.

**Comment by Vort** [comment]
I found one of reproduction cases for empty text:
If I drag "System Text" to position, which not crosses red line (means that text is invisible right now).
I don't think this is intended behaviour.
_(will try to make test you mentioned soon)_

**Comment by Vort** [comment]
Looks like problem was actually with my browser - Vivaldi is not Chrome enough.
The reason I did not saw results with Chrome earlier is that I tested it inside virtual machine and it is laggy.
And I know why it happens - because this project uses video capture. I think more reliably would be to use WebCodecs and craft (multiplex) container "manually".
(Test results: [cat_vivaldi.webm](https://user-images.githubusercontent.com/1242858/193494163-ccdc7ab8-22b2-4d58-a00e-4d00ef201831.webm), [cat_chrome.webm](https://user-images.githubusercontent.com/1242858/193494183-220682e7-7340-4534-9024-a438c32026eb.webm))
By the way I have also reproduction for text disappearing: open program, click new project, drag text, save project, refresh page (F5), click new project, open project.
Because main problem was me thinking that all Chromium browsers are equal, this ticket can be closed now.
Or you can chase text disappearance problems first and close ticket afterwards.

**Comment by toshusai** [comment]
Thank you for investigating. This project also works with Electron (Windows is WIP). Native apps are preferred as browsers cannot easily access local files.

**Comment by Vort** [comment]
I decided not to be lazy and make proper reports for problems with text strips.
