### ISSUE TITLE
Text strip disappears upon clicking if it was created at negative time position

### ISSUE THREAD

**Issue by Vort** [toshusai/Vega#26]
If I drag text strip too far to the left when creating it, it creates corrupted and disappear when I click on it:

[vega_strip_2.webm](https://user-images.githubusercontent.com/1242858/193524213-3fe8afa8-e08e-482c-9c30-62d96c71f435.webm)

**Comment by toshusai** [comment]
[BUG]: Dragging the strip across the timeline leaves a dummy strip behind.
