### ISSUE TITLE
Build or run instructions

### ISSUE THREAD

**Issue by Vort** [toshusai/Vega#29]
With previous versions (3.x) it was possible to
1. Follow the link and run software in browser.
2. Download binaries and run software without browser.

Will these methods be available also with version 4.x ?
If not, will there be instructions with description of how to build this software by yourself?

**Comment by toshusai** [comment]
v4 is no longer supported running in browser officially. sorry for poor docs. You can build just `yarn build`. 
(v4.0.0 release in GitHub is broken).
