### ISSUE TITLE
Module not found: Can't resolve '@/riapp-ui'

### ISSUE THREAD

**Issue by studentofcoding** [toshusai/Vega#30]
When building the project it keeps failing as @riapp-ui is missing, and can't be install manually

```
error - ./utils/registerGlobalVar.ts:5:0
Module not found: Can't resolve '@/riapp-ui'
  3 | 
  4 | import * as Core from "@/core";
> 5 | import * as RiAppUi from "@/riapp-ui";
  6 | 
  7 | export function registerGlobalVar() {
  8 |   if (typeof window !== "undefined") {
  ```
  
  Is there any other way to handle this? thanks

**Comment by toshusai** [comment]
Added dependencies. Can you try again with HEAD?

**Comment by toshusai** [comment]
Additional fix required.  I plan to fix it in the near future.

**Comment by joshuavalenci** [comment]
I had 

> When building the project it keeps failing as @riapp-ui is missing, and can't be install manually
> 
> ```
> error - ./utils/registerGlobalVar.ts:5:0
> Module not found: Can't resolve '@/riapp-ui'
>   3 | 
>   4 | import * as Core from "@/core";
> > 5 | import * as RiAppUi from "@/riapp-ui";
>   6 | 
>   7 | export function registerGlobalVar() {
>   8 |   if (typeof window !== "undefined") {
> ```
> 
> Is there any other way to handle this? thanks

I had this issue but all I did was uninstall yarn then node.js and clean all of the files like cache data so that I can do a clean install then when I did install both node and yarn back I installed the yarn items then I installed npm items if you don't know how to do that you do "yarn" and for npm you do "npm i" or "npm install" and after your done with this you do "npm run dev" if you want more of the commands you can open the package.json file and it will show all the words that you can use in the place of dev it will be under "scripts". Anyways hope that helps you a bit more

**Comment by joshuavalenci** [comment]
So I found a temp fix for this just make a index.ts script inside of the folder named "riapp-ui" and put this script inside it.
`export * from "./src/Card";
export * from "./src/DropdownLike";
export * from "./src/DropdownMenu";
export * from "./src/Modal";
export * from "./src/ModalBody";
export * from "./src/NumberEditInput";
export * from "./src/PanelBody";
export * from "./src/ScaleScrollBar";
export * from "./src/TimeCursor";
export * from "./src/TimeView";
export * from "./src/ToolbarButton";
export * from "./src/TransparentIconButton";
export * from "./src/VInput";
export * from "./src/VSelect";
export * from "./src/VTextarea";
export * from "./src/iconProps";
export * from "./src/hooks";
export * from "./src/panel";
export * from "./src/styled";
export * from "./src/utils";
export * from "./src/context_menu";`

**Comment by toshusai** [comment]
返信が遅れて申し訳ありません。
内部で使用している別のパッケージに依存しており。それをビルドしないと起動しません。

```
cd src/riapp-ui
yarn
yarn build
```

**Comment by toshusai** [comment]
I apologize for the delay in my response. This system has a dependency on another package that needs to be built in order for it to run.

Please try running the following commands and then run yarn dev:

bash
Copy code
cd src/riapp-ui
yarn
yarn build
I am planning to eventually extract the internal UI library into a separate package.

**Comment by toshusai** [comment]
I apologize for the delay in my response. This system has a dependency on another package that needs to be built in order for it to run.

Please try running the following commands and then run `yarn dev`

```
cd src/riapp-ui
yarn
yarn build
```

I am planning to eventually extract the internal UI library into a separate package.
