### ISSUE TITLE
Can we discuss ?

### ISSUE THREAD

**Issue by Easy47** [toshusai/Vega#31]
Hello, I tried to contact you on Twitter because it is the only contact you provide but Twitter no longer allows to send messages.
Would it be possible to chat by email, discord or something else? I would like to ask you a few questions and discuss Vega. Thanks in advance :)

**Comment by toshusai** [comment]
Could you kindly provide an overview or brief description of the topics you would like to discuss?

**Comment by Easy47** [comment]
Thank you for your answer. I need a webapp like Vega for a future project. I wanted to discuss with you to find out if it would be possible to build on this project and under what conditions. Also if you would be interested in doing it personally etc. Have a good day

**Comment by toshusai** [comment]
Certainly, I understand. While I'm not sure how helpful I can be, I am more than willing to discuss the matter further. I find that communication via chat tends to be smoother than email, so may I suggest that we continue our conversation on Discord? Additionally, I have enabled Direct Messages on X(Twitter), so feel free to contact me there if it is more convenient for you.

**Comment by Easy47** [comment]
I agree. This is my discord Easy#6495. Text me whenever you want !
