### ISSUE TITLE
On resizing the strip using left handle, right side of the the strip is cutting instead of left side.

### ISSUE THREAD

**Issue by prarthanashr04** [toshusai/Vega#32]
Initially ,
![initial ss](https://github.com/toshusai/Vega/assets/60914533/941774fe-09b6-4e7f-a5f1-d4d03714187e)

after resizing from left side
![after resizing](https://github.com/toshusai/Vega/assets/60914533/44219771-8054-4eb9-8deb-b74a0c2d301e)

What should I change in the formula to calculate this? so that it can resize from left side .?

**Comment by toshusai** [comment]
It doesn't seems like Vega. But if you want to do that, move the offset instead of the start on resize the left side of strip.

**Comment by prarthanashr04** [comment]
It is the older version, It worked , thanks
