### ISSUE TITLE
 Updating Video Assets in the Project

### ISSUE THREAD

**Issue by prarthanashr04** [toshusai/Vega#34]
Hello,
I'm encountering an issue with updating video assets in my project. Here's a summary of the problem:
Context: I'm fetching data from an API and updating the video assets in the project.
Problem: Direct updates to the video work fine, but when I search for a video (which involves a server-side search and API call), the strip becomes empty.
Specific Issue: When I update project.assets in editor.vue, the strip is not getting updated. Additionally, I see an "undefined" asset in videostrip.ts after searching, and I'm not sure how the following function is getting called:
![afterSearching](https://github.com/toshusai/Vega/assets/60914533/31f9a56d-6afe-4092-b037-ab807ac4d658)
![beforeSearching](https://github.com/toshusai/Vega/assets/60914533/c331f8b4-60b7-4573-92ac-3029ad341779)

public updateAsset(asset?: VideoAsset) {
  console.log(asset, "asset");
  this.setCanvasSize();
  if (!asset) {
    this.video.src = "";
    this.loaded = false;
    return;
  }
  this.videoAsset = asset;
  this.loaded = false;
  asset.valid = false;
  const onLoad = () => {
    if (!this.canvas) return;
    if (this.loaded) return;
    this.videoDuration = this.video.duration;
    this.canvas.width = this.previewWidth;
    this.canvas.height = this.previewHeight;

    this.obj.geometry = new T.PlaneGeometry(
      this.canvas.width,
      this.canvas.height
    );

    this.loaded = true;
    asset.valid = true;
    this.event.dispatchEvent(new CustomEvent("update"));
  };
  this.video.onloadedmetadata = () => onLoad();
  this.video.src = asset.path;
  this.video.load();
}
Additional Context:
The issue seems to occur only after searching.
I suspect the updateAsset function is being called somewhere unexpectedly.
Could you please help me understand how to ensure that the strip gets updated correctly after a search and why the updateAsset function might be receiving an undefined asset?

**Comment by toshusai** [comment]
I'm sorry, but Vega is a personal project. I can't provide support for the code of projects using Vega.
