### ISSUE TITLE
how resolve it

### ISSUE THREAD

**Issue by Hxmic** [toshusai/Vega#35]
<img width="977" alt="image" src="https://github.com/user-attachments/assets/2cef7ede-0a1d-448e-a23d-cec156d12684">

**Comment by Hxmic** [comment]
app-ui   is  empty

**Comment by Hxmic** [comment]
download zip    and  git clone     app-ui   empty

**Comment by Hxmic** [comment]
1、git clone https://github.com/toshusai/Vega.git
2、git clone https://github.com/toshusai/app-ui.git

**Comment by Hxmic** [comment]
resolve

**Comment by Hxmic** [comment]
<img width="565" alt="image" src="https://github.com/user-attachments/assets/38b4ce7d-573e-4bd1-a8b6-3f0a979e1b30">

**Comment by toshusai** [comment]
The app-ui is provided as a submodule.
Please try running the following command within the vega repository:

```
git submodule update --init
```
