### ISSUE TITLE
実行方法を教えて下さい。

### ISSUE THREAD

**Issue by yosshii50** [toshusai/Vega#36]
始めまして、yosshii50 と申します。

下記手順でインストール/実行していますがエラーになります。
何か手順を間違えていますか？教えていただけると助かります。
```
git clone https://github.com/toshusai/Vega.git
npm i
npm run dev
```
よろしくお願いします。

**Comment by toshusai** [comment]
ご返信遅れてしまい申し訳ありません。
mainブランチでは別のリポジトリをサブモジュールとして利用しています。

[こちらのissue](https://github.com/toshusai/Vega/issues/35#issue-2496161787)をご参照頂けると幸いです。
